### ISSUE TITLE
Is $ExpectError useful?

### ISSUE THREAD

**Issue by danvk** [danvk/typings-checker#18]
Any expected error along the lines of `Property 'foo' does not exist on type Bar` could be written as an `$ExpectType` assertion. The [ramda typings][1], for example, use `$ExpectType` far more than `$ExpectError`.

The downside of `$ExpectError` is that it prevents tests from running through `tsc` successfully (since they contain errors). If we dropped `$ExpectError` and only had `$ExpectType`, then `typings-checker` could be run _in addition to_ `tsc`, rather than instead of it. This would make it easier to integrate into DefinitelyTyped.

See https://github.com/Microsoft/types-publisher/pull/292

[1]: https://github.com/types/npm-ramda/blob/3b83e7079772c970a5b770c7f5d32dad3ac24dbc/tests/test.ts

**Comment by danvk** [comment]
cc @tycho01 — could we drop `$ExpectError`?

**Comment by tycho01** [comment]
It's right I hadn't really incorporated `$ExpectError` much so far.
I'm a bit on the fence about ditching it. I'd sorta used it as acknowledging errors as legitimate, with the intention of verifying this behavior without having to remove the tests for tsc.

I think sometimes triggering errors is sort of the point (indicating incorrect usage), which would imply these cases might merit testing, which tsc currently prohibits, as it verifies passing, not expectations.

I can see that not using it would yield a test file that'd pass tsc, but for the Ramda typings file I feel inclined to say that'd be a sacrifice I'm willing to make there.
Differently put, if your library already keeps me aware of such issues, what value is added by looking at tsc shouting about these errors?
As a typing definition repo, I don't need to perform run-time tests, so even without emitting a js version of my tests I'm good. Testing compile-time expectations was the point.

I'm curious about your considerations here though.
And if regular TS libraries start using this to test compile-time expectations, I'll concede those might have different needs which probably would include compiling/running. That said, I don't think `$ExpectError` prevents this as long as it's not canceling things with error status codes.

If I might add a related question: does the functionality hurt if people could opt not to use it?

**Comment by tycho01** [comment]
That said, this is not a feature I feel strongly about.
If you feel dropping it facilitates proliferation, go for it.

**Comment by danvk** [comment]
My inclination is to leave it in but make it optional. Should it be on by default or off? I'm not sure.

**Comment by tycho01** [comment]
I'd be fine with default disabled, it wouldn't hurt me much -- even if you'd remove it that's fine.
Perhaps a (big-ish?) readme note along the lines of "by the way tsc doesn't like errors in case you hadn't noticed" might be simpler though?
