### ISSUE TITLE
Error TS2345 when compiling

### ISSUE THREAD

**Issue by gcanti** [danvk/typings-checker#24]
Running `tsc` (v2.2.1) on the codebase raises the following error

```
src/checker.ts(118,52): error TS2345: Argument of type '{ assertion: { line: number; }; }' is not assignable to parameter of type 'Partial<NodedAssertion>'.
  Types of property 'assertion' are incompatible.
    Type '{ line: number; }' is not assignable to type 'Assertion'.
      Type '{ line: number; }' is not assignable to type 'ErrorAssertion'.
        Property 'kind' is missing in type '{ line: number; }'.
```

Seems a problem related to the definition of `_.find`

**Comment by danvk** [comment]
I'm not seeing this at `HEAD`:

```
$ tsc --version
Version 2.2.1
$ tsc
(no errors)
```

Have you changed the dependencies?

**Comment by gcanti** [comment]
mmh maybe a different version of `@types/lodash`?

mine is `@types/lodash@4.14.53` (`npm install`ed 20 mins ago)

**Comment by danvk** [comment]
You should be using yarn!

**Comment by gcanti** [comment]
Ah! I missed the yarn.lock file. I guess it means that I should use the 4.14.50 version. Sorry for the noise
