### ISSUE TITLE
runtime error when including directives

### ISSUE THREAD

**Issue by tycho01** [danvk/typings-checker#3]
test file:
```
// $ExpectType number
123;
```
Error:
```[ { kind: 'type', type: 'number', line: 1 } ]

typecheck.ts:98
throw new Error('Unable to attach nodes to all assertions.');
```
As soon as I remove the directive line it'd run okay. I'm kind of confused, I appear to run into this on any permutation I could think of. Might you have seen this before by any chance?

**Comment by danvk** [comment]
Here's what I see:

```
$ cat issue3.ts
// $ExpectType number
123;

$ ts-node typecheck.ts issue3.ts
issue3.ts:1: Expected type
  number
but got:
  123

Successes: 0
Failures: 1
```

It fails, but the error is sensible.

**Comment by danvk** [comment]
I've added automated tests (see #4). If you've got a reproducible example, please send a PR with the test file that makes typings-checker explode. The failure should show up on CircleCI.

**Comment by tycho01** [comment]
Dunno what happened, but with some package reinstalling it seems this vanished. Sorry for bugging! :)
